### ISSUE TITLE
Extension Host is angry with `bitlang.cobol` after upgrade to 7.6

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#286]
**Describe the bug**
The extension host has an unhanded startup exception that prevents other extensions from starting. Started happening after upgrade to `7.6` releases. Appears to be a side-effect of the extension cleanup process that the extension host runs not being done yet.

**To Reproduce**
1. Install old extension version
2. Open Output view to `Log (Extension Host)`
3. Install new extension version
4. Reload
5. Scroll through log to exception trace

**Expected behavior**
No exceptions from startup and extensions after this one are allowed to startup without issue.

**Screenshots**
N/A

```
[2021-06-09 10:46:40.755] [exthost] [error] Activating extension bitlang.cobol failed due to an error:
[2021-06-09 10:46:40.755] [exthost] [error] TypeError: e.toLowerCase is not a function
	at ~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:137464
	at Function.init (~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:137756)
	at ~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:156383
	at Generator.next (<anonymous>)
	at ~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:143878
	at new Promise (<anonymous>)
	at s (~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:143623)
	at t.activate (~\.vscode\extensions\bitlang.cobol-7.6.7\dist\extension.js:2:154708)
	at Function._callActivateOptional (~\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:92:14813)
	at Function._callActivate (~\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:92:14486)
	at ~\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:92:12643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Version 7.6.7

**What user & workspace settings are being used?:**
N/A

**Additional context**
N/A

**Comment by spgennard** [comment]
Sorry unable to reproduce.

```json
[2021-06-09 18:04:39.042] [exthost] [info] ExtensionService#_doActivateExtension bitlang.cobol {"startup":false,"extensionId":{"value":"bitlang.cobol","_lower":"bitlang.cobol"},"activationEvent":"onStartupFinished"}
[2021-06-09 18:04:39.042] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/spg/.vscode/extensions/bitlang.cobol-7.6.7/dist/extension
[2021-06-09 18:07:14.053] [exthost] [info] ExtensionService#_doActivateExtension bitlang.cobol {"startup":false,"extensionId":{"value":"bitlang.cobol","_lower":"bitlang.cobol"},"activationEvent":"onFileSystem:file"}
[2021-06-09 18:07:14.053] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/spg/.vscode/extensions/bitlang.cobol-7.6.7/dist/extension

```

**Comment by kabel** [comment]
Didn't intend for my title humor to invoke emotion. Can we agree that it's possible for an otherwise hard to reproduce exception `TypeError` to be thrown by the extension at startup without being caught by the extension?

Clearly an assumed non-null string is being acted on when it's null.

**Comment by spgennard** [comment]
Reverse engineering the code and looking at the code, it appears in onstartup/activate code, if process_metadata_cache_on_start is set and the e.toLowerCase() is generated due to the following typescript:

```typescript
const depMode = settings.cache_metadata !== CacheDirectoryStrategy.Off;
```

I will add a try/catch around the area but I suspect it might be a good time to remove the very hacky "process_metadata_cache_on_start" property, which already affects startup time for some people.

You have not said if after exiting/restart vscode it works for you, can you say?

**Comment by kabel** [comment]
Yes, I imagined it had something to do with the meta cache, just didn't dig into the obfuscated source. Thanks for looking. I know it can affect startup time, but it's a feature I've come to rely on.

I deleted the `.vscode` and `.vscode_cobol` folders that keep getting recreated and restart the window a couple times and it eventually fixes itself. But yes, if the intellisense across copybooks is all ironed out with a new, fast way it's probably time for me to learn about those settings. I'm still not a fan of the extension modifying my `.vscode\settings.json` file, but that seems to be your chosen path forward.
